import Navbar from "../components/navbar/page"
import Sidebar from "../components/sidebar/page"
import '../globals.css'
import { Nunito_Sans } from 'next/font/google'

const nunito = Nunito_Sans({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function DashboardLayout({ children }) {
  return (
      <section>
      <div className='flex flex-col md:flex-col'>
      <Navbar/>
      <div className='flex flex-row md:flex-row'>
      <Sidebar/>
      {children}
      </div>
      </div>
      </section>
  )
}















